import Course from '../entities/Course';
import Structure from '../entities/Structure';
import CompareCourseService from '../services/CompareCourseService';

describe('CompareCourseService', () => {
    it('Should compare course contents with structure templates', () => {
        const course = Course.create({
            courseId: '123',
            name: 'Course Test',
            contents: [
                {
                    id: '1',
                    name: 'New Content',
                    description: 'Its a new content',
                    disponibility: true,
                    type: 'document',
                    hasChildren: true,
                    children: [
                        {
                            id: '2',
                            name: 'New Content 2 ',
                            description: 'Its a new content',
                            disponibility: true,
                            type: 'document',
                            hasChildren: false,
                            parentId: '1',
                        },
                    ],
                },
                {
                    id: '3',
                    name: 'New Content 3',
                    description: 'Its a new content',
                    disponibility: true,
                    type: 'document',
                    beforeId: '1',
                    hasChildren: false,
                },
                {
                    id: '4',
                    name: 'New Content 4',
                    description: 'Its a new content',
                    disponibility: true,
                    type: 'document',
                    beforeId: '3',
                    parentId: '',
                    hasChildren: false,
                },
                {
                    id: '77',
                    name: 'New Content 67',
                    description: 'Its a new content',
                    disponibility: true,
                    type: 'document',
                    beforeId: '4',
                    parentId: '',
                    hasChildren: false,
                },
            ],
        });

        const structure = Structure.create({
            name: 'Test Structure',
            templates: [
                {
                    id: '2',
                    name: 'New Content',
                    nameAlt: '',
                    description: '',
                    descriptionAlt: '',
                    isOptional: false,
                    warnIfNotFound: true,
                    beforeId: '',
                    beforeAlt: [],
                    xor: ['2', '4', '5'],
                    hasNameOfCourseInContent: false,
                    disponibility: true,
                    type: 'document',
                    hasChildren: true,
                    parentId: '',
                    children: [
                        {
                            id: '3',
                            name: 'New Content 2 ',
                            nameAlt: '',
                            description: '',
                            descriptionAlt: '',
                            isOptional: false,
                            warnIfNotFound: true,
                            beforeId: '',
                            beforeAlt: [],
                            xor: [],
                            hasNameOfCourseInContent: false,
                            disponibility: true,
                            type: 'document',
                            hasChildren: false,
                            children: [],
                            parentId: '2',
                        },
                    ],
                },
                {
                    id: '4',
                    name: 'New Content 3',
                    nameAlt: '',
                    description: '',
                    descriptionAlt: '',
                    isOptional: false,
                    warnIfNotFound: true,
                    beforeId: '',
                    beforeAlt: ['2'],
                    xor: ['2', '4', '5'],
                    hasNameOfCourseInContent: false,
                    disponibility: true,
                    type: 'document',
                    hasChildren: false,
                    children: [],
                    parentId: '',
                },
                {
                    id: '5',
                    name: 'New Content 4',
                    nameAlt: '',
                    description: '',
                    descriptionAlt: '',
                    isOptional: false,
                    warnIfNotFound: true,
                    beforeId: '',
                    beforeAlt: ['2', '4'],
                    xor: ['2', '4', '5'],
                    hasNameOfCourseInContent: false,
                    disponibility: true,
                    type: 'document',
                    hasChildren: false,
                    parentId: '',
                    children: [
                        {
                            id: '7',
                            name: 'New Content 6',
                            nameAlt: '',
                            description: '',
                            descriptionAlt: '',
                            isOptional: false,
                            warnIfNotFound: true,
                            beforeId: '',
                            beforeAlt: [],
                            xor: ['6', '7', '8'],
                            hasNameOfCourseInContent: false,
                            disponibility: true,
                            type: 'document',
                            children: [],
                            hasChildren: false,
                            parentId: '',
                        },
                    ],
                },
                {
                    id: '6',
                    name: 'New Content 5',
                    nameAlt: '',
                    description: '',
                    descriptionAlt: '',
                    isOptional: false,
                    warnIfNotFound: true,
                    beforeId: '2',
                    beforeAlt: ['4', '5'],
                    xor: ['6', '7', '8', '9'],
                    hasNameOfCourseInContent: false,
                    disponibility: true,
                    type: 'document',
                    children: [],
                    hasChildren: false,
                    parentId: '',
                },
                {
                    id: '8',
                    name: 'New Content 7',
                    nameAlt: '',
                    description: '',
                    descriptionAlt: '',
                    isOptional: false,
                    warnIfNotFound: true,
                    beforeId: '2',
                    beforeAlt: ['4', '5'],
                    xor: ['6', '7', '8', '9'],
                    hasNameOfCourseInContent: false,
                    disponibility: true,
                    type: 'document',
                    children: [],
                    hasChildren: false,
                    parentId: '',
                },
                {
                    id: '9',
                    name: 'New Content 8',
                    nameAlt: '',
                    description: '',
                    descriptionAlt: '',
                    isOptional: false,
                    warnIfNotFound: true,
                    beforeId: '2',
                    beforeAlt: ['4', '5'],
                    xor: ['6', '7', '8', '9'],
                    hasNameOfCourseInContent: false,
                    disponibility: true,
                    type: 'document',
                    hasChildren: false,
                    parentId: '',
                    children: [
                        {
                            id: '10',
                            name: 'New Content 9',
                            nameAlt: '',
                            description: '',
                            descriptionAlt: '',
                            isOptional: false,
                            warnIfNotFound: true,
                            beforeId: '',
                            beforeAlt: [],
                            xor: [],
                            hasNameOfCourseInContent: false,
                            disponibility: true,
                            type: 'document',
                            children: [],
                            hasChildren: false,
                            parentId: '9',
                        },
                    ],
                },
            ],
        });

        const compareService = new CompareCourseService();

        const errors =
            compareService.compareCourseWithStructureAndGenerateErrors(
                structure,
                course,
            );

        console.log(errors);
    });
});
